### ISSUE TITLE
Site Location Not Returning Name

### ISSUE THREAD

**Issue by newnativeabq** [c19-rnd-dashboard/py-api-vac-rnd-dash#154]
Parse site location name during API lookup if not done so.  Review endpoint for join if already stored.

**Comment by newnativeabq** [comment]
Note, import hanging on site location error code 400 from google API's.   Site location lookups should not be processed if they are already in the database.  Opening subtask for name verification prior to calling API.

**Comment by Nestyko** [comment]
oh, are we hitting the API limits? that's not good. will check that later today.

**Comment by newnativeabq** [comment]
I don't think it is API limits.  There are ~1k  site locations getting
updated at every ingest.  I don't think we need to check for new location
information every time.  It would speed things up significantly to run a
check at ingest to see whether a record exists or not, before calling the
search API.
