### ISSUE TITLE
siteLocations data structure

### ISSUE THREAD

**Issue by Nestyko** [c19-rnd-dashboard/py-api-vac-rnd-dash#88]
This is my proposal for `siteLocations` on the backend, would love to know if this is ok, or It can be improved? maybe the lat and long should not be numbers? or maybe some fields should be avoided.

The name is the one that we will display primarily on the front end, if not present on data you should be able to make it from the city, state or google maps API. It can be null or not present, if so we can just show lat and lon.

```json
{
  "brandName": "",
  "chemicalName": "mrna-1273",
  "conditionOrDisease": "covid-19",
  "countries": "united states",
  "countryCodes": "usa",
  "currentStatus": "phase 1",
  "indication": "covid-19",
  "interventionType": "vaccine - prophylactic",
  "moleculeType": "nucleic acid based therapies/vaccines",
  "notes": "mrna-based vaccine",
  "numSites": "2",
  "otherPartners": "cepi",
  "phase": "1",
  "preferredName": "mrna-1273",
  "productId": 1,
  "productType": "",
  "repurposed": "new",
  "sponsors": "moderna,national institute of allergy and infectious diseases",
  "status": "ongoing",
  "therapeuticApproach": "unknown",
  "trialId": "nct04283461",
  "siteLocations": [
    {
      "name": "Hospital Pkwy",
      "city": "San Jose",
      "state": "California",
      "country": "USA",
      "lat": 37.239746,
      "lon": -121.802344
    }
  ]
}
```

**Comment by Nestyko** [comment]
cc: @j10sanders 

BTW do you guys prefer, `lon`,`long` or `longitude`? this is the time to define it.

**Comment by newnativeabq** [comment]
This is dooable.  I'll start working on the lat, lon lookups this weekend.

**Comment by Nestyko** [comment]
To be consistent with google maps API I will work with an object like:

```json
{
    "name": "Here goes the complete name to be displayed",
    "lat": 123,
    "lng": -123,
    "city": "City if present, could be null",
    "state" : "could be null",
    "country": "Country Code if present"
}
```

**Comment by newnativeabq** [comment]
Help with creating repository of lat/lon in advance needed.

**Comment by Nestyko** [comment]
Resolved, thanks @newnativeabq
